const formatAllDay=d=>`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;
const addDay=date=>{const d=new Date(date);d.setDate(d.getDate()+1);return d};
const escIcal=str=>String(str||'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\n/g,'\\n');
export function buildGoogleCalendarUrl(deadline){const start=formatAllDay(deadline.deadline),end=formatAllDay(addDay(deadline.deadline)),params=new URLSearchParams({action:'TEMPLATE',text:deadline.name,dates:`${start}/${end}`,details:`${deadline.description}\n\nSede electrónica: ${deadline.aeatUrl}`});return `https://calendar.google.com/calendar/render?${params.toString()}`}
const stamp=()=>new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';
const event=(d,withLast=true)=>{const start=formatAllDay(d.deadline),end=formatAllDay(addDay(d.deadline));return ['BEGIN:VEVENT',`UID:${d.id}@factugo`,`DTSTAMP:${stamp()}`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,`SUMMARY:${escIcal(d.name)}`,`DESCRIPTION:${escIcal(d.description)}\\n\\nSede electrónica: ${escIcal(d.aeatUrl)}`,'BEGIN:VALARM','TRIGGER:-P7D','ACTION:DISPLAY',`DESCRIPTION:${escIcal(`Recordatorio: ${d.name} vence pronto`)}`,'END:VALARM',...(withLast?['BEGIN:VALARM','TRIGGER:-P1D','ACTION:DISPLAY',`DESCRIPTION:${escIcal(`¡Último día! ${d.name}`)}`,'END:VALARM']:[]),'END:VEVENT'].join('\r\n')};
export function buildICSContent(deadline){return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//FactuGo//Tax Deadlines//ES','CALSCALE:GREGORIAN',event(deadline),'END:VCALENDAR'].join('\r\n')}
export function buildBulkICSContent(deadlines){return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//FactuGo//Tax Deadlines//ES','CALSCALE:GREGORIAN',deadlines.map(d=>event(d,false)).join('\r\n'),'END:VCALENDAR'].join('\r\n')}
export function downloadICS(content,filename){const blob=new Blob([content],{type:'text/calendar;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${filename}.ics`;a.click();URL.revokeObjectURL(url)}
