export const getQuarterFromDate=d=>{const m=new Date(d).getMonth()+1;return m<=3?'Q1':m<=6?'Q2':m<=9?'Q3':'Q4'};
export const getFiscalYearFromDate=d=>new Date(d).getFullYear();
const asLocalDate = value => value instanceof Date ? new Date(value) : new Date(`${String(value).slice(0, 10)}T12:00:00`);
const asIsoDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
export const getOpenQuarterStartDate = (referenceDate = new Date()) => { const date = asLocalDate(referenceDate); const quarterStartMonth = Math.floor(date.getMonth() / 3) * 3; return asIsoDate(new Date(date.getFullYear(), quarterStartMonth, 1, 12)); };
export const getReceivedInvoiceAccountingDate = (invoiceDate, referenceDate = new Date()) => { const originalDate = asLocalDate(invoiceDate); if (Number.isNaN(originalDate.getTime())) return ''; const openQuarterStart = getOpenQuarterStartDate(referenceDate); return originalDate < asLocalDate(openQuarterStart) ? openQuarterStart : asIsoDate(originalDate); };
export const isReceivedInvoiceFromClosedQuarter = (invoiceDate, referenceDate = new Date()) => { const accountingDate = getReceivedInvoiceAccountingDate(invoiceDate, referenceDate); return Boolean(accountingDate && accountingDate !== String(invoiceDate || '').slice(0, 10)); };
export const getQuarterLabel=q=>({Q1:'1er Trimestre (Ene-Mar)',Q2:'2º Trimestre (Abr-Jun)',Q3:'3er Trimestre (Jul-Sep)',Q4:'4º Trimestre (Oct-Dic)'}[q]||q);
export const getQuarterDeadline=(q,y)=>({Q1:`20/04/${y}`,Q2:`20/07/${y}`,Q3:`20/10/${y}`,Q4:`30/01/${y+1}`}[q]);
export function calculateQuarterVAT(invoices){const emitidas=invoices.filter(i=>i.type==='emitida'&&i.status!=='anulada'),recibidas=invoices.filter(i=>i.type==='recibida'&&i.status!=='anulada'),sum=(list,key)=>list.reduce((s,i)=>s+(i[key]||0),0),byRate=list=>list.reduce((o,i)=>{const r=i.iva_rate??21;o[r]||(o[r]={base:0,cuota:0});o[r].base+=i.base_imponible||0;o[r].cuota+=i.iva_amount||0;return o},{}),ivaRepercutido=sum(emitidas,'iva_amount'),ivaSoportado=sum(recibidas,'iva_amount');return {ivaRepercutido,ivaSoportado,resultado:ivaRepercutido-ivaSoportado,baseEmitidas:sum(emitidas,'base_imponible'),baseRecibidas:sum(recibidas,'base_imponible'),totalEmitidas:sum(emitidas,'total'),totalRecibidas:sum(recibidas,'total'),numEmitidas:emitidas.length,numRecibidas:recibidas.length,irpfRetenidoEmitidas:sum(emitidas,'irpf_amount'),irpfSoportadoRecibidas:sum(recibidas,'irpf_amount'),ivaRepercutidoByRate:byRate(emitidas),ivaSoportadoByRate:byRate(recibidas),baseExentasEmitidas:emitidas.filter(i=>i.tipo_operacion&&i.tipo_operacion!=='normal').reduce((s,i)=>s+(i.base_imponible||0),0)}}
export function validateNIF(nif){if(!nif||nif.length<9)return false;return /^[0-9A-Z]{8,9}[A-Z0-9]$/.test(nif.toUpperCase().replace(/[^A-Z0-9]/g,''))}
export const formatCurrency=amount=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(amount||0);
export const formatDate=d=>d?new Date(d).toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'}):'';
