import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowDownLeft, BarChart3, Bell, BookOpen, CalendarDays, Euro, FileText, LayoutDashboard, LayoutTemplate, LogOut, Menu, PlusCircle, Receipt, Settings, Upload, Users } from 'lucide-react';
import { appClient } from '@/api/appClient';
import { cn } from '@/lib/utils';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';

const navItems = [{ path: '/', label: 'Dashboard', icon: LayoutDashboard }, { path: '/facturas', label: 'Facturas', icon: FileText }, { path: '/cobros', label: 'Cobros', icon: Euro }, { path: '/gastos', label: 'Gastos', icon: ArrowDownLeft }, { path: '/plantillas', label: 'Plantillas', icon: LayoutTemplate }, { path: '/digitalizar', label: 'Digitalizar', icon: Upload }, { path: '/nueva-factura', label: 'Nueva Factura', icon: PlusCircle }, { path: '/trimestres', label: 'Trimestres', icon: Receipt }, { path: '/informes', label: 'Informes', icon: BarChart3 }, { path: '/libros-registro', label: 'Libros registro', icon: BookOpen }, { path: '/notificaciones', label: 'Notificaciones', icon: Bell }, { path: '/clientes', label: 'Clientes', icon: Users }, { path: '/configuracion', label: 'Configuración', icon: Settings }];

export default function MobileNav() {
  const location = useLocation(); const [open, setOpen] = useState(false);
  return <header className="fixed left-0 right-0 top-0 z-50 flex h-16 items-center justify-between border-b border-border bg-card px-4"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary"><Receipt className="h-4 w-4 text-primary-foreground" /></div><span className="font-heading text-sm font-bold">FactuGo</span></div><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="rounded-lg p-2 hover:bg-muted"><Menu className="h-5 w-5" /></button></SheetTrigger><SheetContent side="right" className="w-[260px] p-0"><div className="space-y-1 px-3 py-6">{navItems.map(item => { const active = location.pathname === item.path; return <Link key={item.path} to={item.path} onClick={() => setOpen(false)} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-all', active ? 'bg-primary text-primary-foreground' : 'text-foreground/70 hover:bg-muted')}><item.icon className="h-[18px] w-[18px]" /><span>{item.label}</span></Link>; })}<a href="https://sede.agenciatributaria.gob.es/Sede/presentacion-declaraciones-calendario-contribuyente.html" target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-3 rounded-lg bg-muted px-3 py-2.5 text-sm font-medium text-foreground/80 hover:bg-muted/70"><CalendarDays className="h-[18px] w-[18px]" /><span>Calendario AEAT</span></a><div className="mt-4 border-t border-border pt-4"><button onClick={() => appClient.auth.logout()} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><LogOut className="h-[18px] w-[18px]" /><span>Cerrar sesión</span></button></div></div></SheetContent></Sheet></header>;
}
