import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowDownLeft, BarChart3, Bell, BookOpen, CalendarDays, ChevronLeft, ChevronRight, Euro, FileText, LayoutDashboard, LayoutTemplate, LogOut, PlusCircle, Receipt, Settings, Upload, Users } from 'lucide-react';
import { appClient } from '@/api/appClient';
import { cn } from '@/lib/utils';

const navItems = [
  { path: '/', label: 'Dashboard', icon: LayoutDashboard }, { path: '/facturas', label: 'Facturas', icon: FileText }, { path: '/cobros', label: 'Cobros', icon: Euro }, { path: '/gastos', label: 'Gastos', icon: ArrowDownLeft }, { path: '/plantillas', label: 'Plantillas', icon: LayoutTemplate }, { path: '/digitalizar', label: 'Digitalizar', icon: Upload }, { path: '/nueva-factura', label: 'Nueva Factura', icon: PlusCircle }, { path: '/trimestres', label: 'Trimestres', icon: Receipt }, { path: '/informes', label: 'Informes', icon: BarChart3 }, { path: '/libros-registro', label: 'Libros registro', icon: BookOpen }, { path: '/notificaciones', label: 'Notificaciones', icon: Bell }, { path: '/clientes', label: 'Clientes', icon: Users }, { path: '/configuracion', label: 'Configuración', icon: Settings },
];

export default function Sidebar({ collapsed, onToggle }) {
  const location = useLocation();
  return <aside className={cn('fixed left-0 top-0 z-40 flex h-screen flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground transition-all duration-300', collapsed ? 'w-[68px]' : 'w-[240px]')}>
    <div className="flex h-16 items-center border-b border-sidebar-border px-4">{!collapsed ? <div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-sidebar-primary"><Receipt className="h-4 w-4 text-sidebar-primary-foreground" /></div><div><span className="font-heading text-sm font-bold tracking-tight text-sidebar-primary-foreground">FactuGo</span><p className="mt-0.5 text-[10px] leading-none text-sidebar-foreground/50">Gestión Fiscal</p></div></div> : <div className="mx-auto flex h-8 w-8 items-center justify-center rounded-lg bg-sidebar-primary"><Receipt className="h-4 w-4 text-sidebar-primary-foreground" /></div>}</div>
    <nav className="flex-1 space-y-0.5 overflow-y-auto px-2 py-4">{navItems.map(item => { const active = location.pathname === item.path; return <Link key={item.path} to={item.path} title={collapsed ? item.label : undefined} className={cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-all duration-200', active ? 'bg-sidebar-primary text-sidebar-primary-foreground shadow-md' : 'text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground')}><item.icon className={cn('h-[18px] w-[18px] shrink-0', collapsed && 'mx-auto')} />{!collapsed && <span>{item.label}</span>}</Link>; })}</nav>
    <div className="px-2 pb-2"><a href="https://sede.agenciatributaria.gob.es/Sede/presentacion-declaraciones-calendario-contribuyente.html" target="_blank" rel="noreferrer" title={collapsed ? 'Calendario AEAT' : undefined} className="flex items-center gap-3 rounded-lg bg-sidebar-accent/60 px-3 py-2.5 text-sm font-medium text-sidebar-foreground/80 transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"><CalendarDays className={cn('h-[18px] w-[18px] shrink-0', collapsed && 'mx-auto')} />{!collapsed && <span>Calendario AEAT</span>}</a></div>
    <div className="space-y-1 border-t border-sidebar-border p-2"><button onClick={() => appClient.auth.logout()} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-sidebar-foreground/60 transition-all hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"><LogOut className={cn('h-[18px] w-[18px] shrink-0', collapsed && 'mx-auto')} />{!collapsed && <span>Cerrar sesión</span>}</button><button onClick={onToggle} className="flex w-full items-center justify-center rounded-lg py-2 text-sidebar-foreground/40 transition-colors hover:text-sidebar-foreground/70">{collapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button></div>
  </aside>;
}
