import React, { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { appClient } from '@/api/appClient';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Loader2, LayoutTemplate } from 'lucide-react';
import { toast } from '@/components/ui/use-toast';
export default function SaveTemplateDialog({ open, onClose, formData }) { const queryClient=useQueryClient(),[name,setName]=useState(''); const saveMutation=useMutation({mutationFn:()=>appClient.entities.InvoiceTemplate.create({name,type:formData.type,client_name:formData.client_name,client_nif:formData.client_nif,client_address:formData.client_address,concept:formData.concept,items:formData.items?.map(it=>({description:it.description,quantity:it.quantity,unit_price:it.unit_price,iva_rate:it.iva_rate})),iva_rate:formData.iva_rate,irpf_rate:formData.irpf_rate,recargo_equivalencia_rate:formData.recargo_equivalencia_rate,tipo_operacion:formData.tipo_operacion,payment_method:formData.payment_method,notes:formData.notes}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:['invoice-templates']});toast({title:`Plantilla "${name}" guardada`});setName('');onClose();}});return <Dialog open={open} onOpenChange={onClose}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle className="flex items-center gap-2"><LayoutTemplate className="w-5 h-5 text-primary"/>Guardar como plantilla</DialogTitle></DialogHeader><div className="mt-3 space-y-4"><p className="text-sm text-muted-foreground">Se guardará el cliente, las líneas de detalle y la configuración fiscal actual.</p><div className="space-y-2"><Label>Nombre de la plantilla</Label><Input placeholder="Ej: Servicios mensuales Acme" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&name&&saveMutation.mutate()} autoFocus/></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={()=>saveMutation.mutate()} disabled={!name||saveMutation.isPending} className="gap-2">{saveMutation.isPending?<Loader2 className="w-4 h-4 animate-spin"/>:<LayoutTemplate className="w-4 h-4"/>}Guardar</Button></div></div></DialogContent></Dialog>; }
