import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowDownLeft, ArrowUpRight, BookOpen, FileSpreadsheet } from 'lucide-react';
import { appClient } from '@/api/appClient';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import ExportButton from '@/components/ExportButton';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { issuedInvoiceBookRows, receivedInvoiceBookRows } from '@/lib/invoiceBooks';
import { formatCurrency, formatDate } from '@/lib/fiscalUtils';

function BookCard({ icon: Icon, title, description, rows, filename, sheetName, color }) {
  const preview = rows.slice(0, 5);
  return <Card><CardHeader className="gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${color}`}><Icon className="h-5 w-5" /></div><div><CardTitle className="text-base">{title}</CardTitle><CardDescription className="mt-1">{description}</CardDescription></div></div><ExportButton rows={rows} filename={filename} sheetName={sheetName} /></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">{rows.length} factura{rows.length === 1 ? '' : 's'} incluida{rows.length === 1 ? '' : 's'}.</p>{preview.length ? <div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[620px] text-sm"><thead className="bg-muted/50"><tr><th className="px-3 py-2 text-left font-medium">Número</th><th className="px-3 py-2 text-left font-medium">Fecha</th><th className="px-3 py-2 text-left font-medium">Contraparte</th><th className="px-3 py-2 text-right font-medium">Total</th><th className="px-3 py-2 text-left font-medium">Estado</th></tr></thead><tbody>{preview.map((row, index) => { const issued = 'Nº factura' in row; return <tr key={`${row[issued ? 'Nº factura' : 'Nº factura proveedor']}-${index}`} className="border-t"><td className="px-3 py-2">{row[issued ? 'Nº factura' : 'Nº factura proveedor'] || '—'}</td><td className="px-3 py-2">{formatDate(row[issued ? 'Fecha de expedición' : 'Fecha de factura'])}</td><td className="px-3 py-2">{row[issued ? 'Cliente' : 'Proveedor'] || '—'}</td><td className="px-3 py-2 text-right">{formatCurrency(row['Total factura'])}</td><td className="px-3 py-2 capitalize">{row.Estado || '—'}</td></tr>; })}</tbody></table></div> : <div className="rounded-md border border-dashed px-4 py-8 text-center text-sm text-muted-foreground">No hay facturas para este libro en el año seleccionado.</div>}</CardContent></Card>;
}

export default function InvoiceBooks() {
  const currentYear = new Date().getFullYear(); const [year, setYear] = useState(String(currentYear));
  const { data: invoices = [], isLoading } = useQuery({ queryKey: ['invoices'], queryFn: () => appClient.entities.Invoice.list('-date', 500) });
  const years = useMemo(() => { const available = [...new Set(invoices.map(invoice => invoice.fiscal_year).filter(Boolean))].sort((a, b) => b - a); return available.includes(currentYear) ? available : [currentYear, ...available]; }, [invoices, currentYear]);
  const yearInvoices = useMemo(() => invoices.filter(invoice => invoice.fiscal_year === Number(year)), [invoices, year]);
  const issuedRows = useMemo(() => issuedInvoiceBookRows(yearInvoices), [yearInvoices]); const receivedRows = useMemo(() => receivedInvoiceBookRows(yearInvoices), [yearInvoices]);
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-heading font-bold">Libros registro</h1><p className="mt-1 text-sm text-muted-foreground">Exporta los libros de facturas emitidas y recibidas por ejercicio fiscal.</p></div><Select value={year} onValueChange={setYear}><SelectTrigger className="w-[130px]"><SelectValue /></SelectTrigger><SelectContent>{years.map(item => <SelectItem key={item} value={String(item)}>{item}</SelectItem>)}</SelectContent></Select></div>{isLoading ? <div className="rounded-xl border p-8 text-sm text-muted-foreground">Cargando facturas…</div> : <><div className="rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground"><div className="flex items-center gap-2 font-medium text-foreground"><FileSpreadsheet className="h-4 w-4 text-primary" />Ejercicio {year}</div><p className="mt-1">El selector permite consultar y descargar los libros de años anteriores si existen facturas registradas.</p></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><BookCard icon={ArrowUpRight} title="Libro registro de facturas emitidas" description="Operaciones de venta y prestación de servicios." rows={issuedRows} filename={`libro-registro-facturas-emitidas-${year}`} sheetName="Facturas emitidas" color="bg-emerald-100 text-emerald-700" /><BookCard icon={ArrowDownLeft} title="Libro registro de facturas recibidas" description="Compras, gastos y cuotas de IVA soportado." rows={receivedRows} filename={`libro-registro-facturas-recibidas-${year}`} sheetName="Facturas recibidas" color="bg-amber-100 text-amber-700" /></div><p className="flex items-center gap-2 text-xs text-muted-foreground"><BookOpen className="h-3.5 w-3.5" />Revisa la información antes de presentarla ante la AEAT o remitirla a tu asesoría.</p></>}</div>;
}
