import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import JSZip from 'jszip';
import { Link } from 'react-router-dom';
import { appClient } from '@/api/appClient';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { toast } from '@/components/ui/use-toast';
import ExportButton from '@/components/ExportButton';
import SendInvoiceDialog from '@/components/invoices/SendInvoiceDialog';
import { AlertCircle, ArrowDownLeft, ArrowUpRight, CheckCircle2, Clock, Download, MoreHorizontal, PackageOpen, PlusCircle, Search, Send, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { EXPENSE_CATEGORIES, getCategoryConfig } from '@/lib/expenseCategories';
import { invoicesToRows } from '@/lib/exportUtils';
import { formatCurrency, formatDate } from '@/lib/fiscalUtils';
import { cn } from '@/lib/utils';

const statusColors = { borrador: 'bg-muted text-muted-foreground', validada: 'bg-emerald-50 text-emerald-700 border-emerald-200', contabilizada: 'bg-blue-50 text-blue-700 border-blue-200', anulada: 'bg-red-50 text-red-600 border-red-200' };
const paymentStatusConfig = { pendiente: { label: 'Pendiente', icon: Clock, className: 'bg-amber-50 text-amber-700 border-amber-200' }, pagada: { label: 'Pagada', icon: CheckCircle2, className: 'bg-emerald-50 text-emerald-700 border-emerald-200' }, vencida: { label: 'Vencida', icon: AlertCircle, className: 'bg-red-50 text-red-600 border-red-200' } };

export default function Invoices() {
  const [search, setSearch] = useState(''); const [typeFilter, setTypeFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [paymentFilter, setPaymentFilter] = useState('all'); const [categoryFilter, setCategoryFilter] = useState('all'); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState(''); const [amountMin, setAmountMin] = useState(''); const [amountMax, setAmountMax] = useState(''); const [showAdvanced, setShowAdvanced] = useState(false); const [selected, setSelected] = useState(new Set()); const [isZipping, setIsZipping] = useState(false); const [sendInvoice, setSendInvoice] = useState(null); const [bulkDeleteOpen, setBulkDeleteOpen] = useState(false); const [bulkActionPending, setBulkActionPending] = useState(false);
  const queryClient = useQueryClient();
  const { data: invoices = [], isLoading } = useQuery({ queryKey: ['invoices'], queryFn: () => appClient.entities.Invoice.list('-date', 200) });
  const refresh = title => { queryClient.invalidateQueries({ queryKey: ['invoices'] }); toast({ title }); };
  const deleteMutation = useMutation({ mutationFn: id => appClient.entities.Invoice.delete(id), onSuccess: () => refresh('Factura eliminada') });
  const updateStatusMutation = useMutation({ mutationFn: ({ id, status }) => appClient.entities.Invoice.update(id, { status }), onSuccess: () => refresh('Estado actualizado') });
  const updatePaymentMutation = useMutation({ mutationFn: ({ id, payment_status, payment_date }) => appClient.entities.Invoice.update(id, { payment_status, ...(payment_date ? { payment_date } : {}) }), onSuccess: () => refresh('Estado de pago actualizado') });
  const filtered = useMemo(() => invoices.filter(invoice => { const term = search.toLowerCase(); return (!search || invoice.client_name?.toLowerCase().includes(term) || invoice.invoice_number?.toLowerCase().includes(term) || invoice.concept?.toLowerCase().includes(term) || invoice.client_nif?.toLowerCase().includes(term) || String(invoice.total || '').includes(search) || invoice.date?.includes(search)) && (typeFilter === 'all' || invoice.type === typeFilter) && (statusFilter === 'all' || invoice.status === statusFilter) && (paymentFilter === 'all' || (invoice.payment_status || 'pendiente') === paymentFilter) && (categoryFilter === 'all' || invoice.category === categoryFilter) && (!dateFrom || invoice.date >= dateFrom) && (!dateTo || invoice.date <= dateTo) && (!amountMin || invoice.total >= Number(amountMin)) && (!amountMax || invoice.total <= Number(amountMax)); }), [invoices, search, typeFilter, statusFilter, paymentFilter, categoryFilter, dateFrom, dateTo, amountMin, amountMax]);
  const activeFiltersCount = [dateFrom, dateTo, amountMin, amountMax].filter(Boolean).length;
  const toggleSelect = id => setSelected(previous => { const next = new Set(previous); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const toggleSelectAll = () => setSelected(selected.size === filtered.length ? new Set() : new Set(filtered.map(invoice => invoice.id)));
  const bulkUpdatePayment = async payment_status => { const ids = [...selected]; setBulkActionPending(true); try { await appClient.entities.Invoice.bulkUpdate(ids.map(id => ({ id, payment_status, ...(payment_status === 'pagada' ? { payment_date: new Date().toISOString().slice(0, 10) } : {}) }))); refresh(`${ids.length} factura(s) actualizada(s)`); setSelected(new Set()); } catch { toast({ title: 'Error al actualizar facturas', variant: 'destructive' }); } finally { setBulkActionPending(false); } };
  const bulkDelete = async () => { setBulkActionPending(true); try { await Promise.all([...selected].map(id => appClient.entities.Invoice.delete(id))); refresh(`${selected.size} factura(s) eliminada(s)`); setSelected(new Set()); setBulkDeleteOpen(false); } catch { toast({ title: 'Error al eliminar facturas', variant: 'destructive' }); } finally { setBulkActionPending(false); } };
  const downloadZip = async () => { const items = filtered.filter(invoice => selected.has(invoice.id) && invoice.file_url); if (!items.length) return toast({ title: 'Sin archivos adjuntos', description: 'Las facturas seleccionadas no tienen archivos adjuntos.', variant: 'destructive' }); setIsZipping(true); try { const zip = new JSZip(); await Promise.all(items.map(async invoice => { const blob = await (await fetch(invoice.file_url)).blob(); zip.file(`${invoice.invoice_number || invoice.id}.${invoice.file_url.split('.').pop().split('?')[0] || 'pdf'}`, blob); })); const url = URL.createObjectURL(await zip.generateAsync({ type: 'blob' })); const link = document.createElement('a'); link.href = url; link.download = `facturas-${new Date().toISOString().slice(0, 10)}.zip`; link.click(); URL.revokeObjectURL(url); toast({ title: `ZIP generado con ${items.length} archivo(s)` }); } catch { toast({ title: 'Error al generar el ZIP', variant: 'destructive' }); } finally { setIsZipping(false); } };

  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-heading font-bold">Facturas</h1><p className="text-sm text-muted-foreground mt-1">{invoices.length} facturas registradas</p></div><div className="flex gap-2"><ExportButton rows={invoicesToRows(filtered)} filename={`facturas-${new Date().toISOString().slice(0, 10)}`} sheetName="Facturas" /><Link to="/nueva-factura"><Button size="sm" className="gap-1.5"><PlusCircle className="w-4 h-4" />Nueva factura</Button></Link></div></div>
    <Filters {...{ search, setSearch, typeFilter, setTypeFilter, statusFilter, setStatusFilter, paymentFilter, setPaymentFilter, categoryFilter, setCategoryFilter, dateFrom, setDateFrom, dateTo, setDateTo, amountMin, setAmountMin, amountMax, setAmountMax, showAdvanced, setShowAdvanced, activeFiltersCount }} />
    {selected.size > 0 && <SelectionBar {...{ selected, setSelected, isZipping, downloadZip, bulkActionPending, bulkUpdatePayment, bulkDeleteOpen, setBulkDeleteOpen, bulkDelete }} />}
    <div className="bg-card rounded-xl border border-border overflow-hidden">{isLoading ? <div className="p-6 space-y-3">{[1, 2, 3, 4, 5].map(i => <Skeleton key={i} className="h-12 rounded" />)}</div> : !filtered.length ? <div className="p-12 text-center"><p className="text-muted-foreground text-sm">No se encontraron facturas</p></div> : <div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/50"><TableHead className="w-10 pl-4"><Checkbox checked={selected.size === filtered.length} onCheckedChange={toggleSelectAll} /></TableHead><TableHead className="w-8" /><TableHead>Nº Factura</TableHead><TableHead>Cliente / Proveedor</TableHead><TableHead>Fecha</TableHead><TableHead className="text-right">Base</TableHead><TableHead className="text-right">IVA</TableHead><TableHead className="text-right">Total</TableHead><TableHead>Estado</TableHead><TableHead>Pago</TableHead><TableHead className="w-10" /></TableRow></TableHeader><TableBody>{filtered.map(invoice => <InvoiceRow key={invoice.id} {...{ invoice, selected, toggleSelect, setSendInvoice, updateStatusMutation, updatePaymentMutation, deleteMutation }} />)}</TableBody></Table></div>}</div><SendInvoiceDialog open={!!sendInvoice} onClose={() => setSendInvoice(null)} invoice={sendInvoice} /></div>;
}

function Filters(p) { const clear = () => { p.setDateFrom(''); p.setDateTo(''); p.setAmountMin(''); p.setAmountMax(''); }; return <div className="space-y-3"><div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" /><Input placeholder="Buscar por cliente, nº factura, fecha o importe..." value={p.search} onChange={e => p.setSearch(e.target.value)} className="pl-9" />{p.search && <button onClick={() => p.setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2"><X className="w-3.5 h-3.5" /></button>}</div><FilterSelect value={p.typeFilter} onChange={p.setTypeFilter} label="Todas" values={[['emitida', 'Emitidas'], ['recibida', 'Recibidas']]} /><FilterSelect value={p.statusFilter} onChange={p.setStatusFilter} label="Todos" values={['borrador', 'validada', 'contabilizada', 'anulada'].map(x => [x, x[0].toUpperCase() + x.slice(1)])} /><FilterSelect value={p.paymentFilter} onChange={p.setPaymentFilter} label="Todos los pagos" values={[['pendiente', 'Pendiente'], ['pagada', 'Pagada'], ['vencida', 'Vencida']]} /><Select value={p.categoryFilter} onValueChange={p.setCategoryFilter}><SelectTrigger className="w-[170px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas las categorías</SelectItem>{EXPENSE_CATEGORIES.map(c => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" className={cn('gap-1.5 shrink-0', p.showAdvanced && 'border-primary text-primary')} onClick={() => p.setShowAdvanced(!p.showAdvanced)}><SlidersHorizontal className="w-4 h-4" />Importes{p.activeFiltersCount > 0 && <span className="bg-primary text-primary-foreground rounded-full text-[10px] w-4 h-4">{p.activeFiltersCount}</span>}</Button></div><div className="flex flex-col sm:flex-row gap-3"><Input type="date" value={p.dateFrom} onChange={e => p.setDateFrom(e.target.value)} className="h-8 w-40" /><Input type="date" value={p.dateTo} onChange={e => p.setDateTo(e.target.value)} className="h-8 w-40" />{(p.dateFrom || p.dateTo) && <Button variant="ghost" size="sm" onClick={() => { p.setDateFrom(''); p.setDateTo(''); }}>Limpiar fechas</Button>}</div>{p.showAdvanced && <div className="flex gap-3 p-3 bg-muted/40 rounded-lg border"><Input type="number" placeholder="Importe mín." value={p.amountMin} onChange={e => p.setAmountMin(e.target.value)} /><Input type="number" placeholder="Importe máx." value={p.amountMax} onChange={e => p.setAmountMax(e.target.value)} />{p.activeFiltersCount > 0 && <Button variant="ghost" onClick={clear}>Limpiar</Button>}</div>}</div>; }
function FilterSelect({ value, onChange, label, values }) { return <Select value={value} onValueChange={onChange}><SelectTrigger className="w-[150px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{label}</SelectItem>{values.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>; }
function SelectionBar(p) { return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-primary/5 border border-primary/20 rounded-lg px-4 py-2.5"><span className="text-sm font-medium text-primary">{p.selected.size} factura(s) seleccionada(s)</span><div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={() => p.setSelected(new Set())}><X className="w-3.5 h-3.5" />Deseleccionar</Button><Button size="sm" onClick={p.downloadZip} disabled={p.isZipping}>{p.isZipping ? <PackageOpen className="w-4 h-4 animate-pulse" /> : <Download className="w-4 h-4" />}Descargar ZIP</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" disabled={p.bulkActionPending}>Cambiar pago</Button></DropdownMenuTrigger><DropdownMenuContent>{['pagada', 'pendiente', 'vencida'].map(status => <DropdownMenuItem key={status} onClick={() => p.bulkUpdatePayment(status)}>Marcar como {status}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><AlertDialog open={p.bulkDeleteOpen} onOpenChange={p.setBulkDeleteOpen}><AlertDialogTrigger asChild><Button variant="destructive" size="sm"><Trash2 className="w-4 h-4" />Eliminar</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Eliminar facturas seleccionadas?</AlertDialogTitle><AlertDialogDescription>Esta acción no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={p.bulkDelete}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div>; }
function InvoiceRow({ invoice, selected, toggleSelect, setSendInvoice, updateStatusMutation, updatePaymentMutation, deleteMutation }) { const payment = paymentStatusConfig[invoice.payment_status || 'pendiente']; const PaymentIcon = payment.icon; const category = invoice.category && getCategoryConfig(invoice.category); return <TableRow className={cn('hover:bg-muted/30', selected.has(invoice.id) && 'bg-primary/5')}><TableCell className="pl-4"><Checkbox checked={selected.has(invoice.id)} onCheckedChange={() => toggleSelect(invoice.id)} /></TableCell><TableCell><div className={cn('w-7 h-7 rounded-full flex items-center justify-center', invoice.type === 'emitida' ? 'bg-emerald-50' : 'bg-amber-50')}>{invoice.type === 'emitida' ? <ArrowUpRight className="w-3.5 h-3.5 text-emerald-600" /> : <ArrowDownLeft className="w-3.5 h-3.5 text-amber-600" />}</div></TableCell><TableCell className="font-mono text-xs">{invoice.invoice_number || '—'}</TableCell><TableCell><p className="text-sm font-medium">{invoice.client_name}</p>{invoice.client_nif && <p className="text-xs text-muted-foreground">{invoice.client_nif}</p>}{category && <Badge variant="outline" className={cn('text-[9px]', category.color)}>{category.label}</Badge>}</TableCell><TableCell>{formatDate(invoice.date)}</TableCell><TableCell className="text-right">{formatCurrency(invoice.base_imponible)}</TableCell><TableCell className="text-right">{formatCurrency(invoice.iva_amount)}</TableCell><TableCell className="font-semibold text-right">{formatCurrency(invoice.total)}</TableCell><TableCell><Badge variant="outline" className={cn('text-[10px]', statusColors[invoice.status])}>{invoice.status}</Badge></TableCell><TableCell><Badge variant="outline" className={cn('text-[10px] gap-1', payment.className)}><PaymentIcon className="w-2.5 h-2.5" />{payment.label}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><button className="p-1.5 rounded hover:bg-muted"><MoreHorizontal className="w-4 h-4" /></button></DropdownMenuTrigger><DropdownMenuContent align="end">{invoice.type === 'emitida' && <DropdownMenuItem onClick={() => setSendInvoice(invoice)}><Send className="w-3.5 h-3.5 mr-2" />Enviar al cliente</DropdownMenuItem>}{['validada', 'contabilizada', 'anulada'].map(status => <DropdownMenuItem key={status} onClick={() => updateStatusMutation.mutate({ id: invoice.id, status })}>{status[0].toUpperCase() + status.slice(1)}</DropdownMenuItem>)}{['pagada', 'pendiente', 'vencida'].map(payment_status => <DropdownMenuItem key={payment_status} onClick={() => updatePaymentMutation.mutate({ id: invoice.id, payment_status, payment_date: payment_status === 'pagada' ? new Date().toISOString().slice(0, 10) : undefined })}>Marcar como {payment_status}</DropdownMenuItem>)}<DropdownMenuItem onClick={() => deleteMutation.mutate(invoice.id)} className="text-red-600"><Trash2 className="w-3.5 h-3.5 mr-2" />Eliminar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>; }
