import React, { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { appClient } from '@/api/appClient';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import SaveTemplateDialog from '@/components/invoices/SaveTemplateDialog';
import TemplateSelector from '@/components/invoices/TemplateSelector';
import { LayoutTemplate, Loader2, PlusCircle, Save, Trash2 } from 'lucide-react';
import { toast } from '@/components/ui/use-toast';
import { EXPENSE_CATEGORIES, autoCategorizeExpense } from '@/lib/expenseCategories';
import { formatCurrency, getFiscalYearFromDate, getQuarterFromDate } from '@/lib/fiscalUtils';
import { getNextInvoiceNumber, getNextInvoiceSequence } from '@/lib/invoiceNumber';
import { upsertCounterpartyFromInvoice } from '@/lib/counterparties';

const emptyItem = { description: '', quantity: 1, unit_price: 0, iva_rate: 21, subtotal: 0, iva_amount: 0, total: 0 };
const initialForm = () => ({ type: 'emitida', status: 'contabilizada', payment_status: 'pendiente', payment_date: '', invoice_number: '', date: new Date().toISOString().slice(0, 10), due_date: '', client_name: '', client_nif: '', client_address: '', concept: '', iva_rate: 21, irpf_rate: 0, recargo_equivalencia_rate: 0, tipo_operacion: 'normal', payment_method: 'transferencia', category: 'otros', notes: '', items: [{ ...emptyItem }] });

export default function NewInvoice() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [form, setForm] = useState(initialForm); const [templateSelectorOpen, setTemplateSelectorOpen] = useState(false); const [saveTemplateOpen, setSaveTemplateOpen] = useState(false);
  const { data: profile } = useQuery({ queryKey: ['profile'], queryFn: async () => (await appClient.entities.BusinessProfile.list('-created_date', 1))[0] || null });
  const { data: clients = [] } = useQuery({ queryKey: ['clients'], queryFn: () => appClient.entities.Client.list('name', 100) });
  const { data: invoices = [], isLoading: invoicesLoading } = useQuery({ queryKey: ['invoices'], queryFn: () => appClient.entities.Invoice.list('-created_date', 500) });
  useEffect(() => {
    if (!profile || invoicesLoading) return;
    setForm(previous => ({
      ...previous,
      invoice_number: previous.invoice_number || getNextInvoiceNumber(invoices, profile, previous.date),
      iva_rate: profile.default_iva_rate || 21,
      irpf_rate: previous.type === 'emitida' ? (profile.default_irpf_rate || 15) : 0,
    }));
  }, [profile, invoices, invoicesLoading]);
  const updateField = (field, value) => setForm(previous => { const next = { ...previous, [field]: value }; if (next.type === 'recibida' && (field === 'concept' || field === 'client_name')) next.category = autoCategorizeExpense(next.concept, next.client_name); if (field === 'type') next.irpf_rate = value === 'emitida' ? (profile?.default_irpf_rate ?? 15) : 0; return next; });
  const updateItem = (index, field, value) => setForm(previous => { const items = [...previous.items]; const item = { ...items[index], [field]: value }; const subtotal = (Number(item.quantity) || 0) * (Number(item.unit_price) || 0); items[index] = { ...item, subtotal, iva_amount: subtotal * ((Number(item.iva_rate) || 0) / 100), total: subtotal * (1 + (Number(item.iva_rate) || 0) / 100) }; return { ...previous, items }; });
  const totals = useMemo(() => { const base = form.items.reduce((s, item) => s + (item.subtotal || 0), 0); const iva = form.items.reduce((s, item) => s + (item.iva_amount || 0), 0); const irpf = base * (Number(form.irpf_rate) || 0) / 100; const recargo = base * (Number(form.recargo_equivalencia_rate) || 0) / 100; return { base, iva, irpf, recargo, total: base + iva - irpf + recargo }; }, [form.items, form.irpf_rate, form.recargo_equivalencia_rate]);
  const selectClient = id => { const client = clients.find(item => item.id === id); if (client) setForm(previous => ({ ...previous, client_name: client.name, client_nif: client.nif, client_address: [client.address, client.city, client.postal_code, client.province].filter(Boolean).join(', '), ...(previous.type === 'recibida' ? { category: autoCategorizeExpense(previous.concept, client.name) } : {}) })); };
  const applyTemplate = template => { const items = template.items?.length ? template.items.map(item => { const subtotal = (item.quantity || 1) * (item.unit_price || 0); const iva_amount = subtotal * ((item.iva_rate || 21) / 100); return { ...item, subtotal, iva_amount, total: subtotal + iva_amount }; }) : [{ ...emptyItem }]; setForm(previous => ({ ...previous, type: 'emitida', client_name: template.client_name ?? '', client_nif: template.client_nif ?? '', client_address: template.client_address ?? '', concept: template.concept ?? '', iva_rate: template.iva_rate ?? previous.iva_rate, irpf_rate: template.irpf_rate ?? 0, recargo_equivalencia_rate: template.recargo_equivalencia_rate ?? 0, tipo_operacion: template.tipo_operacion ?? 'normal', payment_method: template.payment_method ?? 'transferencia', notes: template.notes ?? '', items })); toast({ title: `Plantilla "${template.name}" aplicada` }); };
  const saveMutation = useMutation({ mutationFn: async () => { const invoice = await appClient.entities.Invoice.create({ ...form, quarter: getQuarterFromDate(form.date), fiscal_year: getFiscalYearFromDate(form.date), category: form.type === 'recibida' ? (form.category || 'otros') : undefined, base_imponible: totals.base, iva_amount: totals.iva, irpf_amount: totals.irpf, recargo_equivalencia_amount: totals.recargo, total: totals.total }); await upsertCounterpartyFromInvoice(invoice, appClient.entities.Client); return invoice; }, onSuccess: async createdInvoice => { queryClient.invalidateQueries({ queryKey: ['invoices'] }); queryClient.invalidateQueries({ queryKey: ['clients'] }); if (profile && createdInvoice.type === 'emitida') await appClient.entities.BusinessProfile.update(profile.id, { next_invoice_number: getNextInvoiceSequence([...invoices, createdInvoice], profile, createdInvoice.date) }); toast({ title: 'Factura creada correctamente' }); navigate('/facturas'); } });
  const setItems = items => setForm(previous => ({ ...previous, items }));
  return <div className="space-y-6 max-w-4xl"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-heading font-bold">Nueva factura emitida</h1><p className="text-sm text-muted-foreground mt-1">Se contabilizará automáticamente en el trimestre correspondiente</p></div><Button variant="outline" size="sm" className="gap-1.5" onClick={() => setTemplateSelectorOpen(true)}><LayoutTemplate className="w-4 h-4" />Usar plantilla</Button></div>
    <Card><CardHeader className="pb-4"><CardTitle className="text-base">Datos generales</CardTitle></CardHeader><CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4"><TextField label="Nº Factura" value={form.invoice_number} onChange={value => updateField('invoice_number', value)} /><TextField label="Fecha emisión" type="date" value={form.date} onChange={value => updateField('date', value)} /><TextField label="Fecha vencimiento" type="date" value={form.due_date} onChange={value => updateField('due_date', value)} /></CardContent></Card>
    <Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-base">{form.type === 'emitida' ? 'Datos del cliente' : 'Datos del proveedor'}</CardTitle>{clients.length > 0 && <Select onValueChange={selectClient}><SelectTrigger className="w-[200px]"><SelectValue placeholder="Seleccionar" /></SelectTrigger><SelectContent>{clients.filter(client => form.type === 'recibida' ? client.type === 'proveedor' || client.type === 'ambos' : client.type === 'cliente' || client.type === 'ambos').map(client => <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>)}</SelectContent></Select>}</div></CardHeader><CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4"><TextField label="Nombre / Razón social" value={form.client_name} onChange={value => updateField('client_name', value)} /><TextField label="NIF/CIF" value={form.client_nif} onChange={value => updateField('client_nif', value)} /><div className="md:col-span-2"><TextField label="Dirección" value={form.client_address} onChange={value => updateField('client_address', value)} /></div></CardContent></Card>
    <Card><CardHeader className="pb-4"><div className="flex items-center justify-between"><CardTitle className="text-base">Líneas de detalle</CardTitle><Button variant="outline" size="sm" onClick={() => setItems([...form.items, { ...emptyItem, iva_rate: form.iva_rate }])}><PlusCircle className="w-3.5 h-3.5" />Añadir línea</Button></div></CardHeader><CardContent className="space-y-4"><Items items={form.items} updateItem={updateItem} removeItem={index => setItems(form.items.filter((_, i) => i !== index))} /><Totals totals={totals} form={form} /></CardContent></Card>
    <Card><CardContent className="pt-6 grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Forma de pago"><Select value={form.payment_method} onValueChange={value => updateField('payment_method', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['transferencia', 'efectivo', 'tarjeta', 'domiciliacion', 'otro'].map(value => <SelectItem key={value} value={value}>{value === 'domiciliacion' ? 'Domiciliación' : value[0].toUpperCase() + value.slice(1)}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado de pago"><Select value={form.payment_status} onValueChange={value => updateField('payment_status', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['pendiente', 'pagada', 'vencida'].map(value => <SelectItem key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</SelectItem>)}</SelectContent></Select></Field>{form.type === 'recibida' && <Field label="Categoría del gasto"><Select value={form.category || 'otros'} onValueChange={value => updateField('category', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{EXPENSE_CATEGORIES.map(category => <SelectItem key={category.value} value={category.value}>{category.label}</SelectItem>)}</SelectContent></Select></Field>}{form.payment_status === 'pagada' && <TextField label="Fecha de pago" type="date" value={form.payment_date} onChange={value => updateField('payment_date', value)} />}{form.type === 'emitida' && <Field label="Retención IRPF (%)"><div className="flex gap-2">{[0, 7, 9, 15, 20].map(rate => <Button key={rate} type="button" variant={Number(form.irpf_rate) === rate ? 'default' : 'outline'} size="sm" onClick={() => updateField('irpf_rate', rate)}>{rate}%</Button>)}<Input type="number" value={form.irpf_rate} onChange={event => updateField('irpf_rate', event.target.value)} /></div></Field>}<TextField label="Recargo de equivalencia (%)" type="number" value={form.recargo_equivalencia_rate} onChange={value => updateField('recargo_equivalencia_rate', value)} /><Field label="Tipo de operación"><Select value={form.tipo_operacion} onValueChange={value => updateField('tipo_operacion', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[['normal', 'Operación normal'], ['exenta', 'Exenta de IVA'], ['inversion_sujeto_pasivo', 'Inversión del sujeto pasivo'], ['tercer_pais', 'Exportación / Tercer país'], ['canarias_ceuta_melilla', 'Canarias, Ceuta o Melilla'], ['intracomunitaria', 'Operación intracomunitaria']].map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><div className="space-y-2 md:col-span-2"><Label>Observaciones</Label><Textarea value={form.notes} onChange={event => updateField('notes', event.target.value)} rows={3} /></div></CardContent></Card>
    <div className="flex flex-wrap gap-3"><Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}>{saveMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}Guardar factura</Button><Button variant="outline" onClick={() => setSaveTemplateOpen(true)}><LayoutTemplate className="w-4 h-4" />Guardar como plantilla</Button><Button variant="outline" onClick={() => navigate('/facturas')}>Cancelar</Button></div><TemplateSelector open={templateSelectorOpen} onClose={() => setTemplateSelectorOpen(false)} onSelect={applyTemplate} /><SaveTemplateDialog open={saveTemplateOpen} onClose={() => setSaveTemplateOpen(false)} formData={form} /></div>;
}
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function TextField({ label, value, onChange, type = 'text' }) { return <Field label={label}><Input type={type} step={type === 'number' ? '0.01' : undefined} value={value} onChange={event => onChange(event.target.value)} /></Field>; }
function Items({ items, updateItem, removeItem }) { return items.map((item, index) => <div key={index} className="grid grid-cols-12 gap-2 items-end p-3 bg-muted/50 rounded-lg"><div className="col-span-12 md:col-span-4"><TextField label="Descripción" value={item.description} onChange={value => updateItem(index, 'description', value)} /></div><div className="col-span-3 md:col-span-2"><TextField label="Cantidad" type="number" value={item.quantity} onChange={value => updateItem(index, 'quantity', value)} /></div><div className="col-span-3 md:col-span-2"><TextField label="Precio ud." type="number" value={item.unit_price} onChange={value => updateItem(index, 'unit_price', value)} /></div><div className="col-span-3 md:col-span-1"><TextField label="IVA %" type="number" value={item.iva_rate} onChange={value => updateItem(index, 'iva_rate', value)} /></div><div className="col-span-2 md:col-span-2"><Label>Total</Label><p className="text-sm font-semibold py-2">{formatCurrency(item.total)}</p></div><div className="col-span-1">{items.length > 1 && <button onClick={() => removeItem(index)}><Trash2 className="w-4 h-4" /></button>}</div></div>); }
function Totals({ totals, form }) { return <div className="border-t pt-4 space-y-2 max-w-xs ml-auto text-sm"><p className="flex justify-between"><span>Base imponible</span><b>{formatCurrency(totals.base)}</b></p><p className="flex justify-between"><span>IVA</span><b>{formatCurrency(totals.iva)}</b></p>{form.type === 'emitida' && !!Number(form.irpf_rate) && <p className="flex justify-between text-red-600"><span>IRPF ({form.irpf_rate}%)</span><b>-{formatCurrency(totals.irpf)}</b></p>}{!!Number(form.recargo_equivalencia_rate) && <p className="flex justify-between"><span>Recargo</span><b>+{formatCurrency(totals.recargo)}</b></p>}<p className="flex justify-between border-t pt-2 text-base"><b>Total</b><b>{formatCurrency(totals.total)}</b></p></div>; }
