import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { appClient } from '@/api/appClient';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import ExportButton from '@/components/ExportButton';
import { FileDown, FileText, Loader2, Scale, TrendingDown, TrendingUp } from 'lucide-react';
import { invoicesToRows, modelo303ToRows } from '@/lib/exportUtils';
import { calculateQuarterVAT, formatCurrency, getQuarterLabel } from '@/lib/fiscalUtils';
import { generateAnnualPDF } from '@/lib/pdfReportUtils';
const COLORS = ['hsl(210, 62%, 30%)', 'hsl(160, 50%, 40%)'];

export default function Reports() {
  const currentYear = new Date().getFullYear(); const [year, setYear] = useState(String(currentYear)); const [generatingPDF, setGeneratingPDF] = useState(false);
  const { data: profile } = useQuery({ queryKey: ['profile'], queryFn: async () => (await appClient.entities.BusinessProfile.list('-created_date', 1))[0] || null });
  const { data: invoices = [], isLoading } = useQuery({ queryKey: ['invoices'], queryFn: () => appClient.entities.Invoice.list('-date', 500) });
  const yearInvoices = useMemo(() => invoices.filter(invoice => invoice.fiscal_year === Number(year)), [invoices, year]);
  const quarterData = useMemo(() => ['Q1', 'Q2', 'Q3', 'Q4'].map(quarter => { const vat = calculateQuarterVAT(yearInvoices.filter(invoice => invoice.quarter === quarter)); return { name: quarter.replace('Q', 'T'), fullName: getQuarterLabel(quarter), ingresos: vat.baseEmitidas, gastos: vat.baseRecibidas, ivaRepercutido: vat.ivaRepercutido, ivaSoportado: vat.ivaSoportado, resultado: vat.resultado, numFacturas: vat.numEmitidas + vat.numRecibidas }; }), [yearInvoices]);
  const annualTotals = useMemo(() => { const vat = calculateQuarterVAT(yearInvoices); return { ...vat, beneficio: vat.baseEmitidas - vat.baseRecibidas }; }, [yearInvoices]);
  const modelo303 = useMemo(() => quarterData.map(row => ({ trimestre: `Q${row.name.slice(1)}`, label: row.fullName, baseRepercutido: row.ingresos, cuotaRepercutido: row.ivaRepercutido, baseSoportado: row.gastos, cuotaSoportado: row.ivaSoportado, resultado: row.resultado })), [quarterData]);
  const distribution = useMemo(() => [{ name: 'Emitidas', value: yearInvoices.filter(i => i.type === 'emitida' && i.status !== 'anulada').length }, { name: 'Recibidas', value: yearInvoices.filter(i => i.type === 'recibida' && i.status !== 'anulada').length }], [yearInvoices]);
  const years = [...new Set(invoices.map(i => i.fiscal_year).filter(Boolean))].sort((a, b) => b - a); if (!years.includes(currentYear)) years.unshift(currentYear);
  if (isLoading) return <div className="space-y-6">{[1, 2, 3].map(i => <Skeleton key={i} className="h-48 rounded-xl" />)}</div>;
  const pdf = () => { setGeneratingPDF(true); setTimeout(() => { generateAnnualPDF({ annualTotals, quarterData, modelo303, profile, year: Number(year) }); setGeneratingPDF(false); }, 50); };
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-heading font-bold">Informes</h1><p className="text-sm text-muted-foreground mt-1">Análisis fiscal y financiero</p></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={pdf} disabled={generatingPDF || !yearInvoices.length}>{generatingPDF ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}Resumen PDF {year}</Button><ExportButton rows={invoicesToRows(yearInvoices)} filename={`facturas-${year}`} sheetName="Facturas" /><Select value={year} onValueChange={setYear}><SelectTrigger className="w-[120px]"><SelectValue /></SelectTrigger><SelectContent>{years.map(item => <SelectItem key={item} value={String(item)}>{item}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><Kpi icon={TrendingUp} label="Ingresos anuales" value={annualTotals.baseEmitidas} /><Kpi icon={TrendingDown} label="Gastos anuales" value={annualTotals.baseRecibidas} /><Kpi icon={Scale} label="Beneficio neto" value={annualTotals.beneficio} /><Kpi icon={FileText} label="Total facturas" value={yearInvoices.length} plain /></div>
    <Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Vista general</TabsTrigger><TabsTrigger value="iva">IVA Trimestral</TabsTrigger><TabsTrigger value="modelo303">Modelo 303</TabsTrigger></TabsList><TabsContent value="overview" className="space-y-6 mt-6"><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-sm">Ingresos vs Gastos por trimestre</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={300}><BarChart data={quarterData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis tickFormatter={value => `${(value / 1000).toFixed(0)}k`} /><Tooltip formatter={value => formatCurrency(value)} /><Bar dataKey="ingresos" fill={COLORS[0]} name="Ingresos" /><Bar dataKey="gastos" fill="hsl(35, 80%, 55%)" name="Gastos" /></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Distribución de facturas</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={distribution} dataKey="value" cx="50%" cy="50%" innerRadius={60} outerRadius={90}>{distribution.map((_, i) => <Cell key={i} fill={COLORS[i]} />)}</Pie><Legend /><Tooltip /></PieChart></ResponsiveContainer></CardContent></Card></div></TabsContent><TabsContent value="iva" className="mt-6"><Card><CardHeader><CardTitle className="text-sm">Evolución IVA trimestral</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={300}><LineChart data={quarterData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis /><Tooltip formatter={value => formatCurrency(value)} /><Line type="monotone" dataKey="ivaRepercutido" stroke="hsl(152, 60%, 40%)" name="IVA Repercutido" /><Line type="monotone" dataKey="ivaSoportado" stroke="hsl(35, 80%, 55%)" name="IVA Soportado" /><Line type="monotone" dataKey="resultado" stroke={COLORS[0]} name="Resultado" /></LineChart></ResponsiveContainer></CardContent></Card></TabsContent><TabsContent value="modelo303" className="mt-6"><ModeloTable rows={modelo303} year={year} /></TabsContent></Tabs>
  </div>;
}
function Kpi({ icon: Icon, label, value, plain }) { return <Card><CardContent className="p-5"><div className="flex items-center gap-2 mb-2"><Icon className="w-4 h-4 text-primary" /><p className="text-xs text-muted-foreground uppercase">{label}</p></div><p className="text-2xl font-bold">{plain ? value : formatCurrency(value)}</p></CardContent></Card>; }
function ModeloTable({ rows, year }) { const total = key => rows.reduce((sum, row) => sum + row[key], 0); return <Card><CardHeader><div className="flex justify-between"><div><CardTitle className="text-sm">Estructura Modelo 303 — Año {year}</CardTitle><p className="text-xs text-muted-foreground mt-1">Resumen por trimestre</p></div><ExportButton rows={modelo303ToRows(rows, year)} filename={`modelo303-${year}`} sheetName="Modelo 303" /></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{['Trimestre', 'Base IVA devengado', 'Cuota devengado', 'Base deducible', 'Cuota deducible', 'Resultado'].map(header => <th key={header} className="text-right py-3 px-2 text-xs text-muted-foreground first:text-left">{header}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.trimestre} className="border-b"><td className="py-3 px-2 font-medium">{row.label}</td><CellValue value={row.baseRepercutido} /><CellValue value={row.cuotaRepercutido} /><CellValue value={row.baseSoportado} /><CellValue value={row.cuotaSoportado} /><CellValue value={row.resultado} /></tr>)}<tr className="bg-muted/50 font-semibold"><td className="py-3 px-2">TOTAL ANUAL</td>{['baseRepercutido', 'cuotaRepercutido', 'baseSoportado', 'cuotaSoportado', 'resultado'].map(key => <CellValue key={key} value={total(key)} />)}</tr></tbody></table></div></CardContent></Card>; }
function CellValue({ value }) { return <td className="py-3 px-2 text-right">{formatCurrency(value)}</td>; }
