import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, Building2, CreditCard, FileText, Loader2, Save, Upload } from 'lucide-react';
import { appClient } from '@/api/appClient';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from '@/components/ui/use-toast';

const blank = { business_name: '', nif: '', address: '', city: '', postal_code: '', province: '', email: '', phone: '', iban: '', epigraph_iae: '', invoice_prefix: 'F', next_invoice_number: 1, default_iva_rate: 21, default_irpf_rate: 15, logo_url: '', notification_email: '', alert_days_before: 7, irpf_regime: 'pendiente' };

export default function Settings() {
  const queryClient = useQueryClient(); const [form, setForm] = useState(blank);
  const { data: profile, isLoading } = useQuery({ queryKey: ['profile'], queryFn: async () => (await appClient.entities.BusinessProfile.list('-created_date', 1))[0] || null });
  useEffect(() => { if (profile) setForm({ ...blank, ...profile, alert_days_before: profile.alert_days_before ?? 7, irpf_regime: profile.irpf_regime || 'pendiente' }); }, [profile]);
  const update = (field, value) => setForm(previous => ({ ...previous, [field]: value }));
  const saveMutation = useMutation({ mutationFn: () => profile ? appClient.entities.BusinessProfile.update(profile.id, form) : appClient.entities.BusinessProfile.create(form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['profile'] }); toast({ title: 'Configuración guardada' }); } });
  const uploadLogo = async event => { const file = event.target.files?.[0]; if (!file) return; const { file_url } = await appClient.integrations.Core.UploadFile({ file }); update('logo_url', file_url); };
  if (isLoading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>;
  return <div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-heading font-bold">Configuración</h1><p className="mt-1 text-sm text-muted-foreground">Datos fiscales y preferencias de FactuGo</p></div>
    <Section icon={Building2} title="Datos fiscales" description="Información que aparecerá en tus facturas emitidas"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Nombre comercial / Razón social" field="business_name" form={form} update={update} /><Field label="NIF" field="nif" form={form} update={update} /><div className="md:col-span-2"><Field label="Dirección fiscal" field="address" form={form} update={update} /></div><Field label="Ciudad" field="city" form={form} update={update} /><Field label="Código postal" field="postal_code" form={form} update={update} /><Field label="Provincia" field="province" form={form} update={update} /><Field label="Epígrafe IAE" field="epigraph_iae" form={form} update={update} /><Field label="Email" field="email" type="email" form={form} update={update} /><Field label="Teléfono" field="phone" form={form} update={update} /></div></Section>
    <Section icon={FileText} title="Fiscalidad" description="Se utiliza para mostrar obligaciones y estimaciones orientativas"><div className="max-w-md space-y-2"><Label>Régimen de IRPF</Label><Select value={form.irpf_regime} onValueChange={value => update('irpf_regime', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pendiente">No configurado / revisar con asesoría</SelectItem><SelectItem value="estimacion_directa">Estimación directa — Modelo 130</SelectItem><SelectItem value="modulos">Estimación objetiva (módulos) — Modelo 131</SelectItem><SelectItem value="no_aplica">No aplica IRPF trimestral</SelectItem></SelectContent></Select><p className="text-xs text-muted-foreground">Esta selección no sustituye el asesoramiento fiscal ni determina por sí sola tu obligación de presentar el modelo.</p></div></Section>
    <Section icon={CreditCard} title="Datos bancarios"><Field label="IBAN" field="iban" form={form} update={update} placeholder="ES00 0000 0000 0000 0000 0000" /></Section>
    <Section icon={FileText} title="Configuración de facturación"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Prefijo facturas" field="invoice_prefix" form={form} update={update} /><Field label="Siguiente nº factura" field="next_invoice_number" type="number" numeric form={form} update={update} /><Field label="IVA por defecto (%)" field="default_iva_rate" type="number" numeric form={form} update={update} /><Field label="IRPF por defecto (%)" field="default_irpf_rate" type="number" numeric form={form} update={update} /><div className="space-y-2 md:col-span-2"><Label>Logotipo</Label><div className="flex items-center gap-4">{form.logo_url && <img src={form.logo_url} alt="Logo" className="h-16 w-16 rounded-lg border object-contain" />}<label className="cursor-pointer"><span className="flex items-center gap-2 rounded-lg border px-4 py-2 text-sm"><Upload className="h-4 w-4" />Subir logo</span><input type="file" accept="image/*" onChange={uploadLogo} className="hidden" /></label></div></div></div></Section>
    <Section icon={Bell} title="Notificaciones de vencimiento" description="Recibe alertas por email cuando una factura esté próxima a vencer"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Email de notificaciones" field="notification_email" type="email" form={form} update={update} /><Field label="Avisar con X días de antelación" field="alert_days_before" type="number" numeric form={form} update={update} /></div></Section>
    <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}>{saveMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Guardar configuración</Button>
  </div>;
}

function Section({ icon: Icon, title, description, children }) { return <Card><CardHeader><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary" /><CardTitle className="text-base">{title}</CardTitle></div>{description && <CardDescription>{description}</CardDescription>}</CardHeader><CardContent>{children}</CardContent></Card>; }
function Field({ label, field, type = 'text', form, update, numeric, placeholder }) { return <div className="space-y-2"><Label>{label}</Label><Input type={type} value={form[field]} placeholder={placeholder} onChange={event => update(field, numeric ? Number(event.target.value) : event.target.value)} /></div>; }
