import React from 'react';
import { formatCurrency, getQuarterLabel, getQuarterDeadline } from '@/lib/fiscalUtils';
import { cn } from '@/lib/utils';
import { AlertTriangle, CheckCircle2, Clock } from 'lucide-react';

export default function QuarterSummary({ quarter, year, vatData }) {
  const deadline = getQuarterDeadline(quarter, year);
  const isPositive = vatData.resultado > 0;
  return <div className="bg-card rounded-xl border border-border p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-heading font-semibold text-sm">{getQuarterLabel(quarter)}</h3><p className="text-xs text-muted-foreground mt-0.5">Año {year}</p></div><div className="flex items-center gap-1.5 text-xs text-muted-foreground"><Clock className="w-3.5 h-3.5"/><span>Vence: {deadline}</span></div></div><div className="space-y-3"><div className="flex justify-between items-center"><span className="text-xs text-muted-foreground">IVA Repercutido</span><span className="text-sm font-semibold text-emerald-600">+{formatCurrency(vatData.ivaRepercutido)}</span></div><div className="flex justify-between items-center"><span className="text-xs text-muted-foreground">IVA Soportado</span><span className="text-sm font-semibold text-amber-600">-{formatCurrency(vatData.ivaSoportado)}</span></div><div className="h-px bg-border"/><div className="flex justify-between items-center"><span className="text-xs font-medium">Resultado Mod. 303</span><span className={cn('text-base font-bold', isPositive ? 'text-red-600' : 'text-emerald-600')}>{formatCurrency(vatData.resultado)}</span></div><div className="flex items-center gap-1.5 mt-2">{isPositive ? <><AlertTriangle className="w-3.5 h-3.5 text-amber-500"/><span className="text-xs text-amber-600">A ingresar en Hacienda</span></> : <><CheckCircle2 className="w-3.5 h-3.5 text-emerald-500"/><span className="text-xs text-emerald-600">A compensar/devolver</span></>}</div></div><div className="mt-4 pt-3 border-t border-border grid grid-cols-2 gap-2 text-center"><div><p className="text-lg font-bold">{vatData.numEmitidas}</p><p className="text-[10px] text-muted-foreground">Emitidas</p></div><div><p className="text-lg font-bold">{vatData.numRecibidas}</p><p className="text-[10px] text-muted-foreground">Recibidas</p></div></div></div>;
}
