import React, { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, FileText } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import ExportButton from '@/components/ExportButton';
import { formatCurrency } from '@/lib/fiscalUtils';
import { getIntraCommunityOperations, getModel115Rows, getModel130Estimate, getModel303Rows, getModel347Counterparties, getModel349Rows, getModel390Rows, getRentalWithholdingInvoices } from '@/lib/taxModels';

function ModelCard({ model, title, description, tone = 'neutral', children }) {
  const styles = { neutral: 'border-border', pending: 'border-amber-200 bg-amber-50/40', detected: 'border-emerald-200 bg-emerald-50/40' };
  return <Card className={styles[tone]}><CardHeader className="pb-3"><div className="flex items-start gap-3"><div className="rounded-md bg-primary/10 px-2 py-1 font-mono text-xs font-bold text-primary">{model}</div><div><CardTitle className="text-sm">{title}</CardTitle><CardDescription className="mt-1">{description}</CardDescription></div></div></CardHeader><CardContent>{children}</CardContent></Card>;
}

export default function TaxObligations({ invoices, year, quarter, vatData, onOpen303, profile }) {
  const yearInvoices = useMemo(() => invoices.filter(invoice => invoice.fiscal_year === Number(year)), [invoices, year]);
  const quarterInvoices = useMemo(() => yearInvoices.filter(invoice => invoice.quarter === quarter), [yearInvoices, quarter]);
  const rental = useMemo(() => getRentalWithholdingInvoices(quarterInvoices), [quarterInvoices]);
  const intra = useMemo(() => getIntraCommunityOperations(quarterInvoices), [quarterInvoices]);
  const counterparties347 = useMemo(() => getModel347Counterparties(yearInvoices), [yearInvoices]);
  const model130 = useMemo(() => getModel130Estimate(yearInvoices.filter(invoice => ['Q1', 'Q2', 'Q3', 'Q4'].indexOf(invoice.quarter) <= ['Q1', 'Q2', 'Q3', 'Q4'].indexOf(quarter))), [yearInvoices, quarter]);
  const model390Rows = useMemo(() => getModel390Rows(invoices, year), [invoices, year]);
  const irpfRegime = profile?.irpf_regime || 'pendiente';
  return <section className="space-y-4"><div><h2 className="text-lg font-heading font-bold">Obligaciones detectadas</h2><p className="mt-1 text-sm text-muted-foreground">Cálculos de apoyo basados en las facturas contabilizadas en FactuGo.</p></div><div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
    <ModelCard model="303" title="IVA trimestral" description={`Resumen de ${quarter} ${year}.`} tone="detected"><div className="space-y-3"><p className="text-sm">Resultado estimado: <strong>{formatCurrency(vatData.resultado)}</strong></p><div className="flex flex-wrap gap-2"><Button size="sm" onClick={onOpen303}><FileText className="h-4 w-4" />Ver borrador</Button><ExportButton rows={getModel303Rows(vatData, quarter, year)} filename={`borrador-modelo-303-${year}-${quarter}`} sheetName="Borrador 303" /></div></div></ModelCard>
    <ModelCard model="115" title="Retenciones por alquiler" description="Solo procede si has practicado retención en alquileres de inmuebles urbanos." tone={rental.length ? 'detected' : 'neutral'}>{rental.length ? <div className="space-y-3"><p className="text-sm"><strong>{rental.length}</strong> factura{rental.length === 1 ? '' : 's'} detectada{rental.length === 1 ? '' : 's'} · retenciones: <strong>{formatCurrency(rental.reduce((sum, item) => sum + Number(item.irpf_amount || 0), 0))}</strong></p><ExportButton rows={getModel115Rows(rental)} filename={`revision-modelo-115-${year}-${quarter}`} sheetName="Datos 115" /></div> : <p className="text-sm text-muted-foreground">No se han detectado facturas de alquiler con retención.</p>}</ModelCard>
    <ModelCard model={irpfRegime === 'modulos' ? '131' : '130'} title="Pago fraccionado de IRPF" description="Depende de tu régimen de IRPF y de datos no incluidos en las facturas." tone={irpfRegime === 'pendiente' ? 'pending' : 'neutral'}>{irpfRegime === 'pendiente' ? <p className="text-sm"><Link className="font-medium text-primary underline" to="/configuracion">Configura el régimen de IRPF</Link> para activar el cálculo orientativo de este modelo.</p> : irpfRegime === 'modulos' ? <p className="text-sm text-muted-foreground">El modelo 131 se calcula con módulos (actividad, personal, superficie, etc.); FactuGo no puede deducirlos de las facturas.</p> : <div className="space-y-1 text-sm"><p>Rendimiento acumulado estimado: <strong>{formatCurrency(model130.netPerformance)}</strong></p><p>Pago fraccionado estimado: <strong>{formatCurrency(model130.estimatedPayment)}</strong></p><p className="text-xs text-muted-foreground">No incluye pagos previos, minoraciones ni deducciones personales.</p></div>}</ModelCard>
    <ModelCard model="349" title="Operaciones intracomunitarias" description="Se activa si registras operaciones intracomunitarias." tone={intra.length ? 'detected' : 'neutral'}>{intra.length ? <div className="space-y-3"><p className="text-sm"><strong>{intra.length}</strong> operación{intra.length === 1 ? '' : 'es'} marcada{intra.length === 1 ? '' : 's'} como intracomunitaria{intra.length === 1 ? '' : 's'}.</p><ExportButton rows={getModel349Rows(intra)} filename={`revision-modelo-349-${year}-${quarter}`} sheetName="Datos 349" /></div> : <p className="text-sm text-muted-foreground">No hay operaciones intracomunitarias marcadas este trimestre.</p>}</ModelCard>
    <ModelCard model="347" title="Operaciones con terceros" description="Resumen anual por cliente o proveedor." tone={counterparties347.length ? 'detected' : 'neutral'}>{counterparties347.length ? <div className="space-y-3"><p className="text-sm"><strong>{counterparties347.length}</strong> tercero{counterparties347.length === 1 ? '' : 's'} supera{counterparties347.length === 1 ? '' : 'n'} el umbral de 3.005,06 €.</p><ExportButton rows={counterparties347.map(item => ({ 'Cliente/proveedor': item.counterpart, NIF: item.nif, 'Ventas anuales': item.issued, 'Compras anuales': item.received, 'Total anual': item.total, Facturas: item.invoices }))} filename={`revision-modelo-347-${year}`} sheetName="Datos 347" /></div> : <p className="text-sm text-muted-foreground">No hay terceros que superen el umbral anual detectado.</p>}</ModelCard>
    <ModelCard model="390" title="Resumen anual de IVA" description="Consolida los cuatro trimestres del ejercicio." tone="neutral"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm">Preparado para el cierre de {year}.</p><ExportButton rows={model390Rows} filename={`revision-modelo-390-${year}`} sheetName="Resumen 390" /></div></ModelCard>
  </div><div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" /><span>Los Excel/CSV generados son hojas de revisión, no ficheros oficiales para presentar en la AEAT. La presentación y firma se realizan siempre en la Sede AEAT con identificación. Antes de presentar, revisa los datos con tu asesoría.</span></div></section>;
}
